### ISSUE TITLE
gr-dsd ported to GNU Radio 3.10

### ISSUE THREAD

**Issue by fventuri** [argilo/gr-dsd#18]
A few days ago I ported the `gr-dsd` GNU Radio module to build and run under GNU Radio `master` branch (GNU Radio version 3.10), and I was able to listen to a 2m D-STAR repeater nearby using a slightly modified GRC workfllow (https://github.com/fventuri/gr-dsd/blob/gnuradio-3.10/examples/w4rng.grc)

The repository with my changes to `gr-dsd` for GNU radio 3.10 is here: https://github.com/fventuri/gr-dsd/tree/gnuradio-3.10

I also saw Josh Morman's post on the 'gnuradio-discuss' mailing list (https://lists.gnu.org/archive/html/discuss-gnuradio/2021-07/msg00003.html) a few days ago, where he suggests that GNU Radio OOT modules like `gr-dsd` follow a branch naming similar to the one used by GNU Radio.

If you are interested in these changes to make `gr-dsd` compatible with GNU Radio 3.10, please let me know and we can figure out together the best way to incorporate them in your project.

Regards,
Franco Venturi K4VZ

**Comment by argilo** [comment]
Hi Franco! Thanks for offering your code.

I actually just updated gr-dsd to GNU Radio 3.9 (in 135fdb5ce8cbfb6431f1a4fcf1184203f63499c9), and the code appears to work in GNU Radio 3.10 as well.  Since the work is already done, I'll close off this issue. If you happen to notice any problems with the updated code, please let me know.
