### ISSUE TITLE
Does not compile on OSX

### ISSUE THREAD

**Issue by ghost** [argilo/gr-dsd#7]
Would be nice to have it also on the Mac...

[ 69%] Building CXX object lib/CMakeFiles/gr-dsd.dir/dsd_block_ff.cc.o
Linking CXX shared library libgr-dsd.dylib
Undefined symbols for architecture x86_64:
  "pmt::dict_has_key(boost::intrusive_ptrpmt::pmt_base const&, boost::intrusive_ptrpmt::pmt_base const&)", referenced from:
      gr::basic_block::has_msg_port(boost::intrusive_ptrpmt::pmt_base) in dsd_block_ff.cc.o

**Comment by vrl2** [comment]
Thanks for the forked version - I've been struggling for a while now to get it to run in OS X. I compiled the forked version. It compiled, but the module does not show up in gnuradio-companion. Is there another version I should try?

**Comment by LetsGoRosco** [comment]
@vrl2 can you confirm that you used the build instructions for OS X at the bottom of the readme and also ran "sudo make install"? This is the part that will copy the block to the necessary path to be loaded by grc.

It should be installed to /usr/local/share/gnuradio/grc/blocks/dsd_block_ff.xml

This worked for me in version 3.7.8 of gnuradio-companion, I haven't tried the latest version though.

**Comment by vrl2** [comment]
Thank you for getting back to me, and for getting it to work in OSX.

Yes, I ran "sudo make install" after. However, I still received the same
error when launching gnuradio-companion:
"Block key "dsd_block_ff" not found"

I noticed that on startup, gnuradio-companion states the block directory is:
"/opt/local/share/gnuradio/grc/blocks"

I copied the dsd_block_ff.xml file to this directory. This gets rid of the
"block key 'dsd_block_ff' error on startup, and provides a DSD block in
gnuradio-companion. However, if try to use this DSD block, I get an error
when I execute the script:

"Traceback (most recent call last):
  File "/Users/venkat/Desktop/FM_Tuner.py", line 35, in <module>
    import dsd
ImportError: No module named dsd"

I'm running it on gnuradio 3.7.10. If it seems that there is no way to
overcome these errors, I will next try to downgrade to 3.7.8 and report
back any results.

Best,

vrl2

**Comment by LetsGoRosco** [comment]
In that case, it might be worth telling grc to load blocks from the path where the block is installed to (it needs more than just the .xml file)
 
As per the docs: http://gnuradio.org/redmine/projects/gnuradio/wiki/GNURadioCompanion#Method-2-Configuration-File

Create or edit ~/.gnuradio/config.conf and add the following lines:

[grc]
local_blocks_path=/usr/local/share/gnuradio/grc/blocks/

This way the block should be properly loaded. I'll also try updating to 3.7.10 but I won't be able to do this until later in the week.

**Comment by vrl2** [comment]
Thanks for the link. Went through the documentation, and created the
config.conf to add the right path. The DSD block appears in gnuradio, but
at runtime, I still get the error:

"Traceback (most recent call last):
  File "/Users/venkat/Desktop/FM_Tuner.py", line 35, in <module>
    import dsd
ImportError: No module named dsd"

I also tried setting the paths by adding the line
"-DCMAKE_INSTALL_PREFIX=/opt/local"
at build. Gnuradio alerted me to remove the earlier installation to
/usr/local in order to load the DSD block (confirming it successfully
installed to the specified directory). However, I still got the same Import
Error (pasted above) at runtime.

My results were the same on both gnuradio or gnuradio-devel (both 3.7.10).
I've been relying on macports to handle the paths and dependencies, so I
may run into challenges that may prevent installing 3.7.8.  However, if the
procedure is straightforward for rebuilding an out-of-tree module based on
this code, I can try this next. Since I have not built a module before, I
will start by reading GNURadio's documentation:
http://gnuradio.org/redmine/projects/gnuradio/wiki/OutOfTreeModules
unless there are more specific instructions that you might be able to
provide (for example, would PyBombs be a better strategy)?

Thanks again,

**Comment by LetsGoRosco** [comment]
I used macports for 3.7.8 as well, I'll try upgrading to 3.7.10 when I get a chance.

If the module still isn't loaded it could be down to a python version mismatch between how the module is built and how gnuradio-companion is built. Make sure they are using the same version on the same path.

I'd recommend trying to build your own out-of-tree module as per the wiki, that way if you can get your own module to work then you should be able to fix this one.

**Comment by vrl2** [comment]
Some good news - in case there was a python or path version mismatch between the gr-dsd and gnuradio builds, I first checked the version numbers, then substituted the OSX build directions provided in the gr-dsd readme with the ones provided in the gnuradio wiki:
http://gnuradio.org/redmine/projects/gnuradio/wiki/MacInstall

so instead of using:

```
mkdir build
cd build
CC=/usr/bin/llvm-gcc CXX=/usr/bin/llvm-g++ cmake -DPYTHON_EXECUTABLE=/opt/local/bin/python2.7 -DPYTHON_INCLUDE_DIR=/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Headers -DPYTHON_LIBRARY=/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Python ..
make
sudo make install
```

I ran:

```
mkdir build
cd build
CC=/usr/bin/llvm-gcc CXX=/usr/bin/llvm-g++ cmake -DPYTHON_EXECUTABLE=/opt/local/bin/python2.7 -DPYTHON_INCLUDE_DIR=/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Headers -DPYTHON_LIBRARY=/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Python -DSPHINX_EXECUTABLE=/opt/local/bin/rst2html-2.7.py -DGR_PYTHON_DIR=/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages ..
make
sudo make install
```

The build and installation were both successful. Crucially, when I hit execute, the gnuradio workflow now launches the script, instead of halting with the "no module" error mentioned above.

Thanks again for your time. I'll have time to more closely test how it works in 3.7.10 later in the week.

**Comment by argilo** [comment]
I just rebuilt the block using the latest gr_modtool and noticed there's a bunch of OS X stuff in the cmake files. Does this build on OS X now?

**Comment by LetsGoRosco** [comment]
@argilo yes, all i did in my fork was use the latest gr_modtool (at the time).

**Comment by argilo** [comment]
OK, I'll close this issue then. If anyone has trouble installing on OS X, feel free to reopen.
